= Érasme
Théo Daron - Cory De Groote - Léa Durant
:toc:
:title-page:
:toc-title: Table des matières
:pdf-theme: pdf.yml


== Plan de l'exposé

Alors bonjour à tous ! Nous allons donc vous parler d'un auteur humaniste, et plus précisément de Didier Erasme, également appelé Érasme de Rotterdam. Nous commencerons par brièvement vous expliquer ses origines et le cours de sa vie, avant d'analyser deux de ses oeuvres, *Novum Instrumentum* ainsi qu'*Éloge de la folie*.

== Biographie

Comme nous avons pu le lire sur le site _Babelio_, qui est un blog dirigé par 3 passionnés de livres, Érasme serait né aux alentours des années 1465.On ne peut pas vous donner de date plus précise étant donné qu'Érasme est l'enfant illégitime d'un prêtre et d'une fille de médecin, et qu'il n'a pas été formellement déclaré à sa naissance.

Lors de sa scolarité, il sera remarqué par l'église qui assurera son éducation et qui lui donnera une excellente formation de  _latiniste_, formation qui lui servira plus tard afin d'écrire ses œuvres.On retrouve déjà ici une caractéristique humaniste, mais nous y reviendrons par la suite.

Érasme est ce qu'on peut qualifier de *self-made man*, c'est à dire qu'il s'est construit en partant de rien, il n'est pas né dans une famille privilégiée ou haut placée, et pourtant il est encore étudié à l'école à l'heure actuelle.

Ensuite vers ses 18 ans, il deviendra moine, pour ensuite devenir prêtre quelques années plus tard. Mais il s'arrangera auprès de l'Église pour avoir une certaine liberté, et il partira en voyage à travers toute l'Europe, et lors de ces voyages, il va intégrer des cercles humanistes, et il écrira également quelques manuels.C'est à ce moment la qu'Érasme deviendra de plus en plus humanistes.

Pendant ses voyages, vers les années 1500, Erasme se rendra en Angleterre, et il y rencontrera plusieurs figures importantes du courant humaniste, comme *Thomas More*,un juriste et homme politique,grand ami d'Érasme dont nous allons reparler plus tard. En 1503, Érasme publie le _Manuel du chevalier chrétien_, un livre défendant un christianisme épuré, et qui aura une grande influence sur l'humanisme chrétien.

Il continuera ses voyages et reviendra en Angleterre et lors de sa troisième visite il écrira _Éloge de la folie_,un livre dont nous allons reparler plus tard.

Peu après, en 1516, Érasme sort sa propre version du nouveau testament, _Novum Instrumentum omne_, œuvre sur laquelle nous allons revenir plus tard également.

Érasme finit par mourir de la maladie en 1536, à Bâle. <<Babelio>>

== Caractéristiques humanistes d'Érasme

Comme nous l'explique _Claude La Charité_ dans un podcast de radio-canada, Érasme est une des plus grandes figures de l'humanisme. Il a même été surnommé *Le prince des humanistes*. 

Érasme se différencie des autres par son refus de donner son avis et de critiquer la politique. Il préférera aborder d'autres sujets, comme la société, la religion, ou encore l'éducation.De plus, Érasme choisira de s'exprimer uniquement en _latin_, afin d'être compris par toute l'Europe éduquée, l'éducation étant au centre de la pensée humaniste, et donc au centre de la pensée d'Érasme. Au cours de sa vie, Érasme va maintenir un vaste réseau avec tous les gens importants en Europe, que ce soit au niveau politique, littéraire ou religieux. 

Pour le côté religieux, Érasme a passé sa vie au milieu d'un grand dilemme, entre les chrétiens et les protestants. Il restera fidèle à la religion catholique, même s'il adhérait avec toutes les idées et projets des protestants. <<Lacharite>>

== Novum Instrumentum

Le Novum Instrumentum Omne est une traduction du nouveau testament faite par Érasme. Et cette traduction a eu un immense impact sur la théologie, et un impact à long terme, même si a la base, publier cette oeuvre afin qu'elle devienne une de ses principales oeuvres n'était pas vraiment son but, son vrai but était de nettoyer la Vulgate, la traduction latine de Saint Jérome utilisée a l'époque. Cette traduction a été copiée au fil des ans pendant plus d'un millénaire, et s'est forcément corrompue au fil des ans, a cause d'erreurs de traduction, de raccourcis, ou de changements volontaires par les personnes ayant effectué ces copies. Et, selon Érasme, le seul moyen d'avoir la vraie version est de se fier aux textes anciens, donc les textes grecs. Mais malheureusement, les textes originaux n'existaient plus, ils avaient également étés copiés, et donc soumis aux mêmes problèmes que la Vulgate. Érasme a donc voulu reprendre toutes les versions grecques qu'il trouvait, et les comparer entre-elles afin d'essayer d'en reproduire la version originale.

Érasme les a donc analysé dans leur ensemble afin de voir leur différences, et à certains moments, Érasme a du faire des choix pour savoir la version qu'il allait garder, ou pas. Mais Érasme ne s'est pas juste arrêté la, il a également rajouté à son oeuvre des _"Annotations"_, c'est a dire ses réflexions personelles sur la Vulgate et sa traduction, _Annotations_ qui prendront jusqu'a + de 400 pages. 

Malgré tout, la version d'Érasme ne pouvait être parfaite. Érasme a nottament eu des difficultés a traduire l'Apocalypse, partie pour laquelle il ne possédait qu'une seule source, et pour laquelle il a du rétro-transcrire du latin en grec. Mais quelques années plus tard, Érasme a eu accès a d'autres sources, et il a pu corriger une bonne partie de ses erreurs

Mais ce texte n'a pas satisfait tout le monde, et une grosse controverse est née. En effet, pas mal de gens pensaient que c'était les textes grecs, donc les sources d'Érasme, qui étaient le plus corrompus. Ces disputes, qui sont à l'heure actuelle une partie dédiée dans les dernières éditions de son oeuvre, l'ont poursuivi jusqu'a sa mort, en 1536. <<EvangileLiberte>>

== Éloge de la folie

=== Le livre en général

L'éloge de la folie est une *déclamation*. C'est à dire qu'elle est avant tout destinée à être lue et interprétée à voix haute, et pas simplement comme un livre. Cela se rapproche plus du théâtre. Elle a été écrite en _latin_ par Érasme en 1509, et c'est de loin son œuvre la plus connue. Érasme fait parler la déesse Folie, qui va faire sa propre éloge aux hommes. En faisant cela, Érasme fait revenir un genre littéraire de l'Antiquité, l'éloge paradoxale. On retrouve donc ici encore une caractéristique de l'humanisme.Ce genre littéraire vise justement à faire l'éloge de ce qui est habituellement blâmé, la folie en l'occurrence dans ce texte. Dans sa préface (la première partie du livre, précédant l'œuvre), Érasme cite l'éloge de la mouche, une œuvre antique du même genre.

Érasme va dédier ce livre a *Thomas More*, figure célèbre de l'humanisme dont nous avons déjà précédemment parlé, non pas parce qu'il le trouvait fou, mais à cause d'un simple jeu de mot. En grec, la folie se dit _Moria_, ce qui ressemble à _More_, le nom de famille de Thomas. <<Lacharite>>

=== Analyse de deux extraits


Le premier extrait est:
[quote, Erasme, Éloge de la folie - Préface]
Critiquer les mœurs des hommes sans attaquer personne nominativement, est-ce vraiment mordre ? N'est-ce pas plutôt instruire et conseiller ?

Cet extrait se trouve dans la première partie du livre, la préface. Érasme explique que dans son œuvre son objectif était d'instruire et de conseiller. Et c'est pour ça que, comme beaucoup d'humanistes à l'époque, il va se cacher derrière une histoire inventée (ici la folie qui fait sa propre éloge) afin de faire une critique constructive de l'humanité, sans pour autant viser certaines personnes, ce qui pourrait lui attirer des ennuis. On retrouve donc la une deux grandes caractéristiques de l'humanisme, c'est-à-dire la focalisation sur l'être humain, ainsi que l'éducation. Érasme tente même de faire les deux en même temps, il veut éduquer l'être humain afin de l'améliorer. C'est en accord avec la citation _"On ne naît pas homme, on le devient."_.

Le second extrait que nous avons choisi est:

[quote, Erasme, Éloge de la folie]
La guerre n'est-elle pas la source et le théâtre de tous les hauts faits ? Or, quoi de plus fou que d'engager, à propos de je ne sais quoi, une pareille lutte, d'où il résulte toujours, pour les deux partis, plus de mal que de bien ?

Dans cet extrait, Érasme dit, au travers de la folie, que l'être humain est fou, qu'il est fou de faire la guerre et d'en tirer des actes héroïques, alors qu'il n'y a aucune guerre qui finisse bien pour qui que ce soit. On est donc à nouveau sur une critique de l'humain. Érasme veut faire réfléchir et il veut également amener cette réflexion à un apprentissage, à une évolution des conceptions et des idées du lecteur. Il veut rendre l'être humain meilleur.De plus, ici Érasme parle de la guerre, ce qui est également en lien avec l'humanisme, celui-ci étant en faveur de la paix et de la tolérance.

== Conclusion

En conclusion, bien qu'Érasme ne soit pas né privilégié, il a parfaitement réussi à se faire une place parmi les auteurs humanistes de renommée. Il représente l'idéal humaniste.Il est attaché à l'Antiquité, il écrit en latin, et il focalise sur l'humain. 


[bibliography]
== Bibliographie


* [[[Babelio]]] Erasme. (2020). Babelio. Consulté le 28 avril 2022, à l’adresse https://www.babelio.com/auteur/-Erasme/11219


* [[[Lacharite]]] Beauchamp, J., & Lacharité, C. (2022). Érasme, le prince des humanistes [Podcast]. Écouté le 18 avril 2022, sur https://ici.radio-canada.ca/ohdio/premiere/emissions/aujourd-hui-l-histoire/segments/entrevue/195225/erasme-prince-humanistes-claude-charite

* [[[EvangileLiberte]]] Andrist, P. (s. d.). Érasme, le texte grec du Nouveau Testament. . . et l’ironie du destin. Évangile et Liberté. Consulté le 18 avril 2022, à l’adresse https://www.evangile-et-liberte.net/2020/12/la-bible-et-ses-langues/